/* eslint-disable */
/* This file is auto-generated by scripts/ci/generate-api-types.mjs — DO NOT EDIT */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gait-config-version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gait analytics configuration */
        get: operations["getGaitConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fall-risk-config-version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fall risk analytics configuration */
        get: operations["getFallRiskConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics-config-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Combined analytics config versions */
        get: operations["getAnalyticsConfigVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/gait": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a live gait snapshot
         * @description Submit a single gait measurement. Broadcasts to connected WebSocket clients. Rate limit: 120 req/min.
         */
        post: operations["postLiveGait"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/gait/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest batched gait snapshots
         * @description Submit up to 50 gait measurements in one request. Rate limit: 30 req/min.
         */
        post: operations["postLiveGaitBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/gait/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent gait snapshots with rolling statistics */
        get: operations["getLiveGaitRecent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/balance/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report balance test progress
         * @description Submit real-time balance test progress. Broadcasts to WebSocket clients. Rate limit: 120 req/min.
         */
        post: operations["postLiveBalanceProgress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/balance/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit balance test result
         * @description Final balance test result. Rate limit: 30 req/min.
         */
        post: operations["postLiveBalanceResult"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/balance/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent balance test results */
        get: operations["getLiveBalanceRecent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health-data/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process a single health metric
         * @description Validates, enriches with analytics (health score, fall risk, trend), encrypts, and stores in KV. Rate limit: 60 req/min.
         */
        post: operations["postHealthDataProcess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health-data/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process a batch of health metrics
         * @description Process up to 100 metrics in one request. Rate limit: 20 req/min.
         */
        post: operations["postHealthDataBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health-data/analytics/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historical analytics for a user */
        get: operations["getHealthDataAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kv/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a user setting */
        get: operations["getKVValue"];
        /** Write a user setting */
        put: operations["putKVValue"];
        post?: never;
        /** Delete a user setting */
        delete: operations["deleteKVValue"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/2fa/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Two-factor authentication status */
        get: operations["get2FAStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/2fa/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable two-factor authentication */
        post: operations["enable2FA"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/2fa/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable two-factor authentication */
        post: operations["disable2FA"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export user data
         * @description Download a JSON export of server-held user data (GDPR-compliant).
         */
        get: operations["getUserExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/device/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Obtain device JWT
         * @description Exchange device credentials for a short-lived HS256 JWT.
         */
        post: operations["postDeviceAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebSocket upgrade for real-time health data
         * @description Upgrade to WebSocket for live gait/balance streaming and alerts. Without `Upgrade: websocket` header, returns metadata.
         */
        get: operations["getWebSocket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client-error": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report a client-side error
         * @description Submit client errors for analytics and audit logging. Returns a correlationId for tracing.
         */
        post: operations["postClientError"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ws-telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report WebSocket lifecycle events
         * @description Submit client-side WebSocket telemetry (connections, disconnects, errors, latency).
         */
        post: operations["postWsTelemetry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/_perf_ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest RUM performance metrics
         * @description Submit anonymized Real User Monitoring metrics (LCP, TTFB, hydration, CLS, INP). Rate limit: 30 req/min per IP.
         */
        post: operations["postPerfIngest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ws-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebSocket connection URL
         * @description Returns the WebSocket URL for the current environment.
         */
        get: operations["getWsUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ws-live-enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check if live WebSocket streaming is enabled */
        get: operations["getWsLiveEnabled"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** @enum {string} */
        HealthMetricType: "heart_rate" | "walking_steadiness" | "steps" | "gait_speed" | "cadence" | "stride_length" | "step_asymmetry" | "double_support_time" | "posture_angle" | "stability_index" | "sway_balance" | "oxygen_saturation" | "sleep_hours" | "body_weight" | "active_energy" | "distance_walking" | "blood_pressure_systolic" | "blood_pressure_diastolic" | "body_temperature" | "respiratory_rate" | "fall_event";
        /**
         * @example {
         *       "type": "gait_speed",
         *       "value": 1.15,
         *       "unit": "m/s",
         *       "timestamp": "2026-04-12T10:30:00.000Z",
         *       "deviceId": "apple-watch-ultra-2",
         *       "source": "Apple Watch",
         *       "confidence": 0.95
         *     }
         */
        HealthMetric: {
            type: components["schemas"]["HealthMetricType"];
            /** @description Numeric value for the metric */
            value: number;
            unit?: string;
            /** Format: date-time */
            timestamp?: string;
            deviceId?: string;
            userId?: string;
            /** @description Data source (e.g. Apple Watch, manual entry) */
            source?: string;
            /** @description Confidence level of the reading */
            confidence?: number;
        };
        HealthMetricBatch: {
            metrics: components["schemas"]["HealthMetric"][];
            /** Format: date-time */
            uploadedAt: string;
            deviceInfo?: {
                deviceId: string;
                deviceType: string;
                osVersion?: string;
                appVersion?: string;
            };
        };
        /**
         * @example {
         *       "speed": 1.2,
         *       "stepFrequency": 110,
         *       "asymmetry": 0.08,
         *       "variability": 0.12,
         *       "deviceId": "apple-watch-ultra-2",
         *       "source": "ios_device",
         *       "capturedAt": "2026-04-12T10:30:00.000Z"
         *     }
         */
        LiveGaitSnapshot: {
            /** @description Walking speed m/s */
            speed: number;
            /** @description Steps per minute */
            stepFrequency: number;
            asymmetry?: number | null;
            variability?: number | null;
            userId?: string;
            deviceId?: string;
            /** Format: date-time */
            capturedAt?: string;
            /** @default ios_device */
            source: string;
        };
        LiveGaitSnapshotBatch: {
            snapshots: components["schemas"]["LiveGaitSnapshot"][];
            userId?: string;
            deviceId?: string;
            /** Format: date-time */
            capturedAt?: string;
        };
        LiveBalanceProgress: {
            percent: number;
            instantaneousStability?: number | null;
            elapsedSeconds: number;
            testKind?: string;
            userId?: string;
            deviceId?: string;
            /** Format: date-time */
            capturedAt?: string;
        };
        LiveBalanceResult: {
            overallScore: number;
            componentScores: {
                [key: string]: number;
            };
            testKind?: string;
            userId?: string;
            deviceId?: string;
            /** Format: date-time */
            capturedAt?: string;
        };
        ProcessedHealthData: {
            /** Format: uuid */
            id?: string;
            type: components["schemas"]["HealthMetricType"];
            value: number;
            unit?: string;
            /** Format: date-time */
            timestamp: string;
            /** Format: date-time */
            processedAt: string;
            validated: boolean;
            healthScore?: number;
            /** @enum {string} */
            fallRisk?: "low" | "moderate" | "high" | "critical";
            trendAnalysis?: {
                /** @enum {string} */
                direction: "improving" | "stable" | "declining";
                confidence: number;
                changePercent?: number;
            };
            /** @description How unusual this reading is */
            anomalyScore?: number;
            /** @description Related metrics that influenced this reading */
            correlatedMetrics?: string[];
            alert?: {
                /** @enum {string} */
                level: "info" | "warning" | "critical" | "emergency";
                message: string;
                actionRequired?: boolean;
                /** Format: date-time */
                expiresAt?: string;
            } | null;
            source: {
                deviceId?: string;
                userId: string;
                /** Format: date-time */
                collectedAt: string;
                processingPipeline?: string;
            };
            dataQuality?: {
                completeness?: number;
                accuracy?: number;
                timeliness?: number;
                consistency?: number;
            };
        };
        ErrorResponse: {
            error: string;
            details?: Record<string, never>;
        };
        SuccessResponse: {
            /** @constant */
            ok: true;
        };
        ClientError: {
            message: string;
            /**
             * @default window.onerror
             * @enum {string}
             */
            source: "window.onerror" | "unhandledrejection" | "console.error";
            route?: string;
            sessionId?: string;
            ua?: string;
            stack?: string;
            meta?: {
                [key: string]: string;
            };
        };
        WebSocketTelemetry: {
            /** @enum {string} */
            event: "connect_start" | "connect_success" | "connect_error" | "close" | "retry" | "ping_timeout" | "pong_received" | "message_error";
            url?: string;
            attempt?: number;
            code?: number;
            reason?: string;
            backoffMs?: number;
            sinceMs?: number;
            rttMs?: number;
            readyState?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "healthy",
                     *       "timestamp": "2026-04-12T12:00:00.000Z",
                     *       "environment": "production"
                     *     }
                     */
                    "application/json": {
                        /** @enum {string} */
                        status?: "healthy";
                        /** Format: date-time */
                        timestamp?: string;
                        environment?: string;
                    };
                };
            };
        };
    };
    getGaitConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current gait config and version */
            200: {
                headers: {
                    /** @description Config version ETag for conditional requests */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not modified (ETag match) */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFallRiskConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current fall risk config and version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAnalyticsConfigVersions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gait + fall risk config versions (single round-trip) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postLiveGait: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LiveGaitSnapshot"];
            };
        };
        responses: {
            /** @description Snapshot accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized — missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postLiveGaitBatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LiveGaitSnapshotBatch"];
            };
        };
        responses: {
            /** @description Batch accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized — missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getLiveGaitRecent: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent snapshots with rolling averages and trend analysis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postLiveBalanceProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LiveBalanceProgress"];
            };
        };
        responses: {
            /** @description Progress recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized — missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postLiveBalanceResult: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LiveBalanceResult"];
            };
        };
        responses: {
            /** @description Result submitted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized — missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getLiveBalanceRecent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent balance results and last progress */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postHealthDataProcess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HealthMetric"];
            };
        };
        responses: {
            /** @description Processed metric with analytics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessedHealthData"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized — missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postHealthDataBatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HealthMetricBatch"];
            };
        };
        responses: {
            /** @description Batch processing results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                        processed?: number;
                        results?: components["schemas"]["ProcessedHealthData"][];
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized — missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getHealthDataAnalytics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Historical health data array */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessedHealthData"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getKVValue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: "preferences" | "dashboard-layout" | "alert-settings" | "theme" | "notification-settings";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Setting value */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        key?: string;
                        value?: unknown;
                    };
                };
            };
            /** @description Invalid key */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    putKVValue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: "preferences" | "dashboard-layout" | "alert-settings" | "theme" | "notification-settings";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    value: unknown;
                };
            };
        };
        responses: {
            /** @description Setting saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid key or body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteKVValue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Setting deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get2FAStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 2FA status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        enabled?: boolean;
                        /** Format: date-time */
                        updatedAt?: string | null;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    enable2FA: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 2FA enabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                        /** @constant */
                        enabled?: true;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    disable2FA: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 2FA disabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                        /** @constant */
                        enabled?: false;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getUserExport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User data export (JSON file download) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        exportVersion?: number;
                        /** Format: date-time */
                        exportedAt?: string;
                        userId?: string;
                        twoFactor?: {
                            enabled?: boolean;
                            updatedAt?: string | null;
                        };
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postDeviceAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    userId: string;
                    /**
                     * @default ios_app
                     * @enum {string}
                     */
                    clientType?: "ios_app" | "web_dashboard";
                    /** @description Token TTL in seconds */
                    ttlSec?: number;
                };
            };
        };
        responses: {
            /** @description JWT issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                        token?: string;
                        expiresIn?: number;
                    };
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Device auth not configured */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getWebSocket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WebSocket connection established */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description WebSocket metadata (no upgrade header) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                        upgradeRequired?: boolean;
                        /** Format: uri */
                        url?: string;
                        supportedMessageTypes?: string[];
                        analyticsVersions?: {
                            gait?: string;
                            fallRisk?: string;
                        };
                    };
                };
            };
            /** @description Unauthorized (production only) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description WebSocket binding not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postClientError: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientError"];
            };
        };
        responses: {
            /** @description Error recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "ok": true,
                     *       "correlationId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                     *     }
                     */
                    "application/json": {
                        ok?: boolean;
                        /** Format: uuid */
                        correlationId?: string;
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized — missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postWsTelemetry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebSocketTelemetry"];
            };
        };
        responses: {
            /** @description Telemetry recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                        /** Format: uuid */
                        correlationId?: string;
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized — missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postPerfIngest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "v": 1,
                 *       "appVersion": "1.0.0",
                 *       "metrics": {
                 *         "lcp": 1200,
                 *         "ttfb": 150,
                 *         "hydration": 320,
                 *         "cls": 0.05
                 *       }
                 *     }
                 */
                "application/json": {
                    /** @description RUM metrics — only valid keys are: lcp, ttfb, hydration, wsConnect, cls, inp */
                    metrics?: {
                        /** @description Largest Contentful Paint (ms) */
                        lcp?: number;
                        /** @description Time to First Byte (ms) */
                        ttfb?: number;
                        /** @description React hydration time (ms) */
                        hydration?: number;
                        /** @description WebSocket connect time (ms) */
                        wsConnect?: number;
                        /** @description Cumulative Layout Shift */
                        cls?: number;
                        /** @description Interaction to Next Paint (ms) */
                        inp?: number;
                    };
                    /** @description RUM protocol version */
                    v?: number;
                    appVersion?: string;
                };
            };
        };
        responses: {
            /** @description Metrics ingested */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description No valid metrics or invalid payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getWsUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WebSocket URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "url": "wss://health.andernet.dev/ws",
                     *       "fallback": "wss://health.andernet.dev/ws"
                     *     }
                     */
                    "application/json": {
                        /** Format: uri */
                        url?: string;
                        /** Format: uri */
                        fallback?: string;
                    };
                };
            };
        };
    };
    getWsLiveEnabled: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feature flag status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "enabled": true
                     *     }
                     */
                    "application/json": {
                        enabled?: boolean;
                    };
                };
            };
        };
    };
}
