/**
 * Export functionality: PDF, CSV, GeoPackage
 * Deterministic exports with watermarks and version info
 */

export interface ExportOptions {
  format: 'pdf' | 'csv' | 'geopackage'
  includeWatermark?: boolean
  includeMetadata?: boolean
  version?: string
}

export interface ExportResult {
  id: string
  format: string
  url?: string
  filePath?: string
  size: number
  createdAt: string
  metadata: {
    version: string
    watermark?: string
    exportedBy?: string
  }
}

/**
 * Export data to CSV format
 */
export function exportToCSV(
  data: Array<Record<string, any>>,
  options: ExportOptions = { format: 'csv' }
): string {
  if (data.length === 0) {
    return ''
  }

  // Get all unique keys
  const keys = new Set<string>()
  data.forEach((row) => {
    Object.keys(row).forEach((key) => keys.add(key))
  })

  const headers = Array.from(keys)
  const rows: string[] = []

  // Add metadata comment if requested
  if (options.includeMetadata) {
    rows.push(`# Export generated: ${new Date().toISOString()}`)
    if (options.version) {
      rows.push(`# Version: ${options.version}`)
    }
    rows.push('')
  }

  // Add headers
  rows.push(headers.map((h) => escapeCSV(h)).join(','))

  // Add data rows
  data.forEach((row) => {
    const values = headers.map((key) => {
      const value = row[key]
      if (value === null || value === undefined) {
        return ''
      }
      if (typeof value === 'object') {
        return escapeCSV(JSON.stringify(value))
      }
      return escapeCSV(String(value))
    })
    rows.push(values.join(','))
  })

  // Add watermark if requested
  if (options.includeWatermark) {
    rows.push('')
    rows.push(`# Generated by Geospatial Health Platform - ${new Date().toISOString()}`)
  }

  return rows.join('\n')
}

function escapeCSV(value: string): string {
  if (value.includes(',') || value.includes('"') || value.includes('\n')) {
    return `"${value.replace(/"/g, '""')}"`
  }
  return value
}

/**
 * Export GeoJSON to GeoPackage format (simplified - in production use proper GeoPackage library)
 */
export function exportToGeoPackage(
  geojson: {
    type: 'FeatureCollection'
    features: Array<{
      type: 'Feature'
      geometry: any
      properties: Record<string, any>
    }>
  },
  options: ExportOptions = { format: 'geopackage' }
): string {
  // Simplified: return GeoJSON with metadata
  // In production, use proper GeoPackage library (e.g., @ngageoint/geopackage)
  const exportData = {
    ...geojson,
    metadata: {
      exportedAt: new Date().toISOString(),
      version: options.version || '1.0.0',
      watermark: options.includeWatermark
        ? `Geospatial Health Platform - ${new Date().toISOString()}`
        : undefined,
    },
  }

  return JSON.stringify(exportData, null, 2)
}

/**
 * Generate PDF export (simplified - in production use PDF library)
 */
export function exportToPDF(
  content: {
    title: string
    sections: Array<{ heading: string; content: string | any[] }>
    metadata?: Record<string, any>
  },
  options: ExportOptions = { format: 'pdf' }
): string {
  // Simplified: return HTML representation
  // In production, use PDF library (e.g., pdfkit, puppeteer)
  const html = `
<!DOCTYPE html>
<html>
<head>
  <title>${content.title}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; }
    h1 { color: #333; }
    h2 { color: #666; margin-top: 30px; }
    .metadata { background: #f5f5f5; padding: 15px; margin: 20px 0; }
    .watermark { position: fixed; bottom: 10px; right: 10px; color: #ccc; font-size: 10px; }
  </style>
</head>
<body>
  <h1>${content.title}</h1>
  ${options.includeMetadata && content.metadata ? `<div class="metadata"><pre>${JSON.stringify(content.metadata, null, 2)}</pre></div>` : ''}
  ${content.sections
    .map(
      (section) => `
    <h2>${section.heading}</h2>
    ${typeof section.content === 'string' ? `<p>${section.content}</p>` : `<pre>${JSON.stringify(section.content, null, 2)}</pre>`}
  `
    )
    .join('')}
  ${options.includeWatermark ? `<div class="watermark">Geospatial Health Platform - ${new Date().toISOString()}</div>` : ''}
</body>
</html>
  `.trim()

  return html
}

/**
 * Create export record
 */
export function createExport(
  data: any,
  format: ExportOptions['format'],
  options: ExportOptions = {}
): ExportResult {
  const id = `export-${Date.now()}-${Array.from(crypto.getRandomValues(new Uint8Array(11)), b => b.toString(36)).join('').slice(0, 7)}`
  let content: string

  switch (format) {
    case 'csv':
      content = exportToCSV(Array.isArray(data) ? data : [data], options)
      break
    case 'geopackage':
      content = exportToGeoPackage(data, options)
      break
    case 'pdf':
      content = exportToPDF(data, options)
      break
    default:
      throw new Error(`Unsupported format: ${format}`)
  }

  return {
    id,
    format,
    size: Buffer.byteLength(content, 'utf8'),
    createdAt: new Date().toISOString(),
    metadata: {
      version: options.version || '1.0.0',
      watermark: options.includeWatermark
        ? `Geospatial Health Platform - ${new Date().toISOString()}`
        : undefined,
    },
  }
}
