/**
 * Centralized icon re-exports from lucide-react.
 * All application components should import icons from '@/lib/icons' instead of 'lucide-react'.
 * UI primitives (shadcn) in src/components/ui/ are excluded from this convention.
 *
 * lucide-react supports tree-shaking, so unused icons are automatically removed from the bundle.
 *
 * Usage: import { Activity, AlertTriangle } from '@/lib/icons';
 */

export {
  Activity,
  AlertCircle,
  AlertTriangle,
  BarChart3,
  Battery,
  Bell,
  BellRing,
  Bluetooth,
  Brain,
  Bug,
  Calendar,
  Camera,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Clock,
  CloudUpload,
  Database,
  Download,
  FileJson,
  FileSpreadsheet,
  FileText,
  Filter,
  Footprints,
  Gauge,
  Globe,
  Heart,
  Home,
  Lightbulb,
  Loader2,
  Lock,
  MapPin,
  Menu,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  PanelLeft,
  Pause,
  Phone,
  Play,
  Plus,
  Radio,
  RefreshCcw,
  RefreshCw,
  Scan,
  Search,
  Settings,
  Share,
  Shield,
  ShieldCheck,
  Signal,
  Smartphone,
  Sparkles,
  Sun,
  Target,
  Trash,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Upload,
  User,
  Users,
  Watch,
  Wifi,
  WifiOff,
  Wrench,
  X,
  XCircle,
  Zap,
  type LucideIcon,
} from 'lucide-react';

// Alias for Settings to match existing usage
export { Settings as SettingsIcon } from 'lucide-react';
