name = "health-app"
main = "dist-worker/index.js"
compatibility_date = "2024-08-30"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[build]
command = "npm run build:worker"
cwd = "."
watch_dir = "src"

# Assets configuration for React app
[assets]
directory = "./dist"
binding = "ASSETS"

# Development environment
[env.development]
name = "health-app-dev"

[env.development.vars]
ENVIRONMENT = "development"
ALLOWED_ORIGINS = "http://localhost:5173,http://127.0.0.1:5173,http://localhost:5000,http://127.0.0.1:5000"
BASE_URL = "http://localhost:8789"
API_BASE_URL = "http://localhost:8789/api"
WEBSOCKET_URL = "ws://localhost:3001"
FILES_BASE_URL = "http://localhost:8789/files"
LOG_LEVEL = "debug"
FALL_DETECTION_THRESHOLD = "0.75"
EMERGENCY_RESPONSE_DELAY = "30"
MAX_FILE_SIZE = "100MB"
SESSION_TIMEOUT = "24h"

# Production environment
[env.production]
name = "health-app-prod"

[env.production.vars]
ENVIRONMENT = "production"
ALLOWED_ORIGINS = "https://health.andernet.dev"
BASE_URL = "https://health.andernet.dev"
API_BASE_URL = "https://health.andernet.dev/api"
WEBSOCKET_URL = "wss://health.andernet.dev/ws"
FILES_BASE_URL = "https://health.andernet.dev/files"
LOG_LEVEL = "info"
FALL_DETECTION_THRESHOLD = "0.85"
EMERGENCY_RESPONSE_DELAY = "30"
MAX_FILE_SIZE = "500MB"
SESSION_TIMEOUT = "12h"
# Auth0 Configuration
AUTH0_DOMAIN = "dev-qjdpc81dzr7xrnlu.us.auth0.com"
AUTH0_CLIENT_ID = "3SWqx7E8dFSIWapIikjppEKQ5ksNxRAQ"

# Production KV namespaces
[[env.production.kv_namespaces]]
binding = "HEALTH_KV"
id = "c3501957dd2540ccb6f624a78df59936"

# Production Durable Objects
[[env.production.durable_objects.bindings]]
name = "HEALTH_WEBSOCKET"
class_name = "HealthWebSocket"

# Durable Objects
[[durable_objects.bindings]]
name = "HEALTH_WEBSOCKET"
class_name = "HealthWebSocket"

# Migrations for Durable Objects
[[migrations]]
tag = "v1"
new_sqlite_classes = ["HealthWebSocket"]

# Production routes - using zone_name
# [[env.production.routes]]
# pattern = "health.andernet.dev/*"
# zone_name = "andernet.dev"
