# SwiftLint configuration for VitalSense Monitor
# This helps maintain consistent code quality and catches potential issues

# Included rules
included:
  - VitalSenseMonitor/

# Excluded paths
excluded:
  - build/
  - VitalSenseMonitorTests/
  - VitalSenseMonitorUITests/
  - Pods/
  - .build/

# Enabled rules
opt_in_rules:
  - array_init
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Disabled rules
disabled_rules:
  - trailing_whitespace # Can be annoying in some editors
  - todo # Allow TODO comments during development

# Rule configurations
line_length:
  warning: 120
  error: 150

type_body_length:
  warning: 600
  error: 800

file_length:
  warning: 600
  error: 1000

function_body_length:
  warning: 100
  error: 150

# Nesting configuration - removed invalid statement_level key
nesting:
  type_level: 3
  function_level: 5

# Force unwrapping severity
force_unwrapping:
  severity: warning

# Custom rules for HealthKit specific patterns
custom_rules:
  healthkit_auth_check:
    name: "HealthKit Authorization Check"
    regex: 'HKHealthStore\(\)\.requestAuthorization'
    message: "Always check authorization status before requesting HealthKit permissions"
    severity: warning
    
  websocket_error_handling:
    name: "WebSocket Error Handling"
    regex: '\.send\('
    message: "Consider adding proper error handling for WebSocket operations"
    severity: warning
