name = "health-app"
main = "dist-worker/index.js"
compatibility_date = "2024-08-30"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[build]
command = "npm run build:worker"
cwd = "."
watch_dir = "src"

# Assets configuration for React app
[assets]
directory = "./dist"
binding = "ASSETS"

# Production environment (minimal)
[env.production]
name = "health-app-prod"

[env.production.vars]
ENVIRONMENT = "production"
ALLOWED_ORIGINS = "https://health.andernet.dev"
BASE_URL = "https://health.andernet.dev"
LOG_LEVEL = "info"

# Custom domain routes
[[env.production.routes]]
pattern = "health.andernet.dev/*"
zone_name = "andernet.dev"
