name = "health-app-prod"
main = "dist-worker/index.js"
compatibility_date = "2024-08-30"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[build]
command = "npx vite build --config vite.worker.config.ts"
cwd = "."
watch_dir = "src"

# Assets configuration for React app
[assets]
directory = "./dist"
binding = "ASSETS"

# Production environment
[env.production]
name = "health-app-prod"

# Production environment variables
[env.production.vars]
ENVIRONMENT = "production"
ALLOWED_ORIGINS = "https://health.andernet.dev,https://vitalsense.andernet.dev"
BASE_URL = "https://health.andernet.dev"
API_BASE_URL = "https://health.andernet.dev/api"
WEBSOCKET_URL = "wss://health.andernet.dev/ws"
FILES_BASE_URL = "https://health.andernet.dev/files"
LOG_LEVEL = "info"
FALL_DETECTION_THRESHOLD = "0.85"
EMERGENCY_RESPONSE_DELAY = "30"
MAX_FILE_SIZE = "500MB"
SESSION_TIMEOUT = "12h"
ENABLE_ANALYTICS = "true"
ENABLE_SECURITY_LOGGING = "true"
ENABLE_PERFORMANCE_MONITORING = "true"

# Production KV namespaces
[[env.production.kv_namespaces]]
binding = "HEALTH_KV"
id = "c3501957dd2540ccb6f624a78df59936"

# Session storage KV
[[env.production.kv_namespaces]]
binding = "SESSION_KV"
id = "92783e42b1f54805be49a882bc0ef525"

# Cache KV for performance
[[env.production.kv_namespaces]]
binding = "CACHE_KV"
id = "327f94aec89b473db9a4d90baa9a2923"

# Production R2 buckets for file storage
[[env.production.r2_buckets]]
binding = "HEALTH_FILES"
bucket_name = "vitalsense-health-files"

# Audit log storage
[[env.production.r2_buckets]]
binding = "AUDIT_LOGS"
bucket_name = "vitalsense-audit-logs"
