/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LidarPostureRouteImport } from './routes/lidar-posture'
import { Route as GaitAnalysisRouteImport } from './routes/gait-analysis'
import { Route as FallRiskRouteImport } from './routes/fall-risk'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LidarPostureRoute = LidarPostureRouteImport.update({
  id: '/lidar-posture',
  path: '/lidar-posture',
  getParentRoute: () => rootRouteImport,
} as any)
const GaitAnalysisRoute = GaitAnalysisRouteImport.update({
  id: '/gait-analysis',
  path: '/gait-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const FallRiskRoute = FallRiskRouteImport.update({
  id: '/fall-risk',
  path: '/fall-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fall-risk': typeof FallRiskRoute
  '/gait-analysis': typeof GaitAnalysisRoute
  '/lidar-posture': typeof LidarPostureRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fall-risk': typeof FallRiskRoute
  '/gait-analysis': typeof GaitAnalysisRoute
  '/lidar-posture': typeof LidarPostureRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fall-risk': typeof FallRiskRoute
  '/gait-analysis': typeof GaitAnalysisRoute
  '/lidar-posture': typeof LidarPostureRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fall-risk'
    | '/gait-analysis'
    | '/lidar-posture'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fall-risk' | '/gait-analysis' | '/lidar-posture' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/fall-risk'
    | '/gait-analysis'
    | '/lidar-posture'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FallRiskRoute: typeof FallRiskRoute
  GaitAnalysisRoute: typeof GaitAnalysisRoute
  LidarPostureRoute: typeof LidarPostureRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lidar-posture': {
      id: '/lidar-posture'
      path: '/lidar-posture'
      fullPath: '/lidar-posture'
      preLoaderRoute: typeof LidarPostureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gait-analysis': {
      id: '/gait-analysis'
      path: '/gait-analysis'
      fullPath: '/gait-analysis'
      preLoaderRoute: typeof GaitAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fall-risk': {
      id: '/fall-risk'
      path: '/fall-risk'
      fullPath: '/fall-risk'
      preLoaderRoute: typeof FallRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FallRiskRoute: FallRiskRoute,
  GaitAnalysisRoute: GaitAnalysisRoute,
  LidarPostureRoute: LidarPostureRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
