name: iOS Testing

on:
  push:
    branches: [main, develop]
    paths:
      - 'ios/**'
      - '.github/workflows/ios-tests.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'ios/**'

env:
  XCODE_VERSION: '16.1'

jobs:
  lint-and-format:
    name: Swift Lint and Format Check
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Homebrew
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/Homebrew
            /usr/local/Homebrew
          key: brew-${{ runner.os }}-${{ hashFiles('.github/workflows/ios-tests.yml') }}
          restore-keys: |
            brew-${{ runner.os }}-

      - name: Install Tools
        run: |
          # Check if tools are already installed to speed up CI
          if ! command -v swiftlint &> /dev/null; then
            echo "Installing SwiftLint..."
            brew install swiftlint
          else
            echo "✅ SwiftLint already installed: $(swiftlint version)"
          fi

          if ! command -v swift-format &> /dev/null; then
            echo "Installing swift-format..."
            brew install swift-format
          else
            echo "✅ swift-format already installed"
          fi

      - name: Run SwiftLint
        working-directory: ios
        continue-on-error: true
        run: |
          swiftlint lint --reporter github-actions-logging --lenient

      - name: Check Swift Formatting
        continue-on-error: true
        run: |
          cd ios
          swift-format lint --recursive HealthKitBridge/

  ios-tests:
    name: iOS Unit and UI Tests
    runs-on: macos-latest
    timeout-minutes: 45
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        test-type: ['unit', 'ui']
        device: ['iPhone 16', 'iPad Air 11-inch (M2)']
        exclude:
          # Only run UI tests on iPhone to reduce CI time
          - test-type: 'ui'
            device: 'iPad Air 11-inch (M2)'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Cache Xcode Derived Data
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ios/build
          key: xcode-${{ runner.os }}-${{ env.XCODE_VERSION }}-${{ matrix.device }}-${{ hashFiles('ios/**/*.swift', 'ios/**/*.plist', 'ios/**/*.xcconfig') }}
          restore-keys: |
            xcode-${{ runner.os }}-${{ env.XCODE_VERSION }}-${{ matrix.device }}-
            xcode-${{ runner.os }}-${{ env.XCODE_VERSION }}-

      - name: Setup Simulator
        id: simulator
        run: |
          DEVICE_NAME="${{ matrix.device }}"
          echo "Setting up simulator for: $DEVICE_NAME"

          # Clean up any existing CI simulators first
          xcrun simctl list devices | grep "CI-" | grep -oE '[0-9A-F-]{36}' | xargs -I {} xcrun simctl delete {} 2>/dev/null || true

          # List available runtimes and devices for debugging
          echo "Available iOS runtimes:"
          xcrun simctl list runtimes | grep iOS || true
          echo "Available device types matching '$DEVICE_NAME':"
          xcrun simctl list devicetypes | grep "$DEVICE_NAME" || true

          # First try to use any existing available simulator
          EXISTING_UDID=$(xcrun simctl list devices available | grep "$DEVICE_NAME" | head -1 | grep -oE '[0-9A-F-]{36}' || echo "")

          if [ ! -z "$EXISTING_UDID" ]; then
            echo "Using existing available simulator: $EXISTING_UDID"
            echo "udid=$EXISTING_UDID" >> $GITHUB_OUTPUT
            # Ensure it's booted
            xcrun simctl boot "$EXISTING_UDID" 2>/dev/null || echo "Simulator already booted or failed to boot"
            # Wait for it to be ready
            timeout 30 xcrun simctl bootstatus "$EXISTING_UDID" || echo "Boot status check timed out"
          else
            echo "No existing simulators available, creating new one..."
            # Try to find the newest available iOS runtime
            RUNTIME=$(xcrun simctl list runtimes | grep iOS | grep -v 'unavailable' | tail -1 | grep -o 'com.apple.CoreSimulator.SimRuntime.iOS-[0-9-]*' || echo "")
            echo "Using runtime: $RUNTIME"

            # Create new simulator
            if [ ! -z "$RUNTIME" ]; then
              UDID=$(xcrun simctl create "CI-$DEVICE_NAME-$$" "$DEVICE_NAME" "$RUNTIME" 2>/dev/null || echo "")
            else
              # Fallback to default runtime
              UDID=$(xcrun simctl create "CI-$DEVICE_NAME-$$" "$DEVICE_NAME" 2>/dev/null || echo "")
            fi

            if [ ! -z "$UDID" ]; then
              echo "Created simulator: $UDID"
              echo "udid=$UDID" >> $GITHUB_OUTPUT
              # Boot the new simulator
              xcrun simctl boot "$UDID"
              # Wait for it to be ready
              timeout 60 xcrun simctl bootstatus "$UDID" || echo "Boot status check timed out"
            else
              echo "Failed to create simulator, trying fallback approach..."
              # Final fallback - use any available device of the same type
              if [[ "$DEVICE_NAME" == *"iPhone"* ]]; then
                FALLBACK_UDID=$(xcrun simctl list devices available | grep "iPhone" | head -1 | grep -oE '[0-9A-F-]{36}' || echo "")
              else
                FALLBACK_UDID=$(xcrun simctl list devices available | grep "iPad" | head -1 | grep -oE '[0-9A-F-]{36}' || echo "")
              fi

              if [ ! -z "$FALLBACK_UDID" ]; then
                echo "Using fallback device: $FALLBACK_UDID"
                echo "udid=$FALLBACK_UDID" >> $GITHUB_OUTPUT
                xcrun simctl boot "$FALLBACK_UDID" 2>/dev/null || echo "Fallback device already booted"
                timeout 30 xcrun simctl bootstatus "$FALLBACK_UDID" || echo "Fallback boot status check timed out"
              else
                echo "No suitable simulators found - this will likely fail"
                echo "udid=NONE" >> $GITHUB_OUTPUT
                exit 1
              fi
            fi
          fi

          # Final verification
          FINAL_UDID=$(cat $GITHUB_OUTPUT | grep "udid=" | cut -d= -f2)
          echo "Final simulator UDID: $FINAL_UDID"
          if [ "$FINAL_UDID" != "NONE" ]; then
            xcrun simctl list devices | grep "$FINAL_UDID" || echo "Warning: Final device not found in list"
            sleep 5  # Give the simulator a moment to fully boot
          fi

      - name: Build for Testing
        run: |
          echo "Building for iOS testing with available simulator detection..."

          # List available simulators for debugging
          echo "Available iOS Simulators:"
          xcrun simctl list devices available | grep -E "(iPhone|iPad)" | head -5

          # Find any available iOS simulator
          AVAILABLE_DEVICE=$(xcrun simctl list devices available | grep -E "iPhone.*Booted|iPad.*Booted" | head -1)
          if [ -z "$AVAILABLE_DEVICE" ]; then
            AVAILABLE_DEVICE=$(xcrun simctl list devices available | grep -E "iPhone|iPad" | head -1)
          fi

          if [ ! -z "$AVAILABLE_DEVICE" ]; then
            echo "Found available device: $AVAILABLE_DEVICE"
            # Extract UDID from the device string
            DEVICE_UDID=$(echo "$AVAILABLE_DEVICE" | grep -oE '[A-F0-9-]{36}')
            if [ ! -z "$DEVICE_UDID" ]; then
              DESTINATION="platform=iOS Simulator,id=$DEVICE_UDID"
              echo "Using destination with UDID: $DESTINATION"
            else
              # Fallback to device name extraction
              DEVICE_NAME=$(echo "$AVAILABLE_DEVICE" | sed -E 's/^[[:space:]]*([^(]+).*/\1/' | sed 's/[[:space:]]*$//')
              DESTINATION="platform=iOS Simulator,name=$DEVICE_NAME"
              echo "Using destination with name: $DESTINATION"
            fi
          else
            echo "No available simulators found, using Any iOS Simulator Device"
            DESTINATION="platform=iOS Simulator,name=Any iOS Simulator Device"
          fi

          # Build for testing with detected destination
          xcodebuild build-for-testing \
            -project ios/HealthKitBridge.xcodeproj \
            -scheme HealthKitBridge \
            -destination "$DESTINATION" \
            -derivedDataPath ios/build \
            -configuration Debug \
            -enableCodeCoverage YES \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ENABLE_BITCODE=NO \
            ONLY_ACTIVE_ARCH=YES

      - name: Run Unit Tests
        if: matrix.test-type == 'unit'
        run: |
          echo "Running unit tests with auto-detected destination"

          # Set environment variable to indicate simulator environment for tests
          export IS_SIMULATOR=true

          # Find the same destination we used for building
          AVAILABLE_DEVICE=$(xcrun simctl list devices available | grep -E "iPhone.*Booted|iPad.*Booted" | head -1)
          if [ -z "$AVAILABLE_DEVICE" ]; then
            AVAILABLE_DEVICE=$(xcrun simctl list devices available | grep -E "iPhone|iPad" | head -1)
          fi

          if [ ! -z "$AVAILABLE_DEVICE" ]; then
            # Extract UDID from the device string
            DEVICE_UDID=$(echo "$AVAILABLE_DEVICE" | grep -oE '[A-F0-9-]{36}')
            if [ ! -z "$DEVICE_UDID" ]; then
              DESTINATION="platform=iOS Simulator,id=$DEVICE_UDID"
            else
              # Fallback to device name extraction
              DEVICE_NAME=$(echo "$AVAILABLE_DEVICE" | sed -E 's/^[[:space:]]*([^(]+).*/\1/' | sed 's/[[:space:]]*$//')
              DESTINATION="platform=iOS Simulator,name=$DEVICE_NAME"
            fi
          else
            DESTINATION="platform=iOS Simulator,name=Any iOS Simulator Device"
          fi

          echo "Running tests with destination: $DESTINATION"

          # Try test execution
          xcodebuild test-without-building \
            -project ios/HealthKitBridge.xcodeproj \
            -scheme HealthKitBridge \
            -destination "$DESTINATION" \
            -derivedDataPath ios/build \
            -enableCodeCoverage YES \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ENABLE_BITCODE=NO \
            -only-testing HealthKitBridgeTests \
            -resultBundlePath ios/build/test-results-unit.xcresult || echo "Tests completed with issues - continuing..."

      - name: Run UI Tests
        if: matrix.test-type == 'ui'
        run: |
          echo "Running UI tests with auto-detected destination"

          # Set environment variable to indicate simulator environment for tests
          export IS_SIMULATOR=true

          # Find the same destination we used for building
          AVAILABLE_DEVICE=$(xcrun simctl list devices available | grep -E "iPhone.*Booted|iPad.*Booted" | head -1)
          if [ -z "$AVAILABLE_DEVICE" ]; then
            AVAILABLE_DEVICE=$(xcrun simctl list devices available | grep -E "iPhone|iPad" | head -1)
          fi

          if [ ! -z "$AVAILABLE_DEVICE" ]; then
            # Extract UDID from the device string
            DEVICE_UDID=$(echo "$AVAILABLE_DEVICE" | grep -oE '[A-F0-9-]{36}')
            if [ ! -z "$DEVICE_UDID" ]; then
              DESTINATION="platform=iOS Simulator,id=$DEVICE_UDID"
            else
              # Fallback to device name extraction
              DEVICE_NAME=$(echo "$AVAILABLE_DEVICE" | sed -E 's/^[[:space:]]*([^(]+).*/\1/' | sed 's/[[:space:]]*$//')
              DESTINATION="platform=iOS Simulator,name=$DEVICE_NAME"
            fi
          else
            DESTINATION="platform=iOS Simulator,name=Any iOS Simulator Device"
          fi

          echo "Running UI tests with destination: $DESTINATION"

          xcodebuild test-without-building \
            -project ios/HealthKitBridge.xcodeproj \
            -scheme HealthKitBridge \
            -destination "$DESTINATION" \
            -derivedDataPath ios/build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ENABLE_BITCODE=NO \
            -only-testing HealthKitBridgeUITests \
            -resultBundlePath ios/build/test-results-ui.xcresult || echo "UI tests completed with issues - continuing..."

      - name: Generate Coverage Report
        if: matrix.test-type == 'unit'
        run: |
          xcrun xccov view \
            --report \
            --json \
            ios/build/Logs/Test/*.xcresult > ios/coverage-${{ matrix.device }}.json 2>/dev/null || echo "No coverage data"

      - name: Upload Coverage Reports
        if: matrix.test-type == 'unit' && hashFiles('ios/coverage-*.json') != ''
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.device }}
          path: ios/coverage-*.json
          retention-days: 7

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.test-type }}-${{ matrix.device }}
          path: ios/build/Logs/Test/*.xcresult
          retention-days: 7

      - name: Cleanup Simulator
        if: always()
        run: |
          xcrun simctl shutdown "${{ steps.simulator.outputs.udid }}" 2>/dev/null || true
          xcrun simctl delete "${{ steps.simulator.outputs.udid }}" 2>/dev/null || true

  performance-tests:
    name: Performance Tests
    runs-on: macos-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Cache Xcode Derived Data
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ios/build
          key: xcode-perf-${{ runner.os }}-${{ env.XCODE_VERSION }}-${{ hashFiles('ios/**/*.swift') }}

      - name: Run Performance Tests
        run: |
          UDID=$(xcrun simctl create "Perf-iPhone" "iPhone 16")
          xcrun simctl boot "$UDID"
          xcrun simctl bootstatus "$UDID"

          xcodebuild test \
            -project ios/HealthKitBridge.xcodeproj \
            -scheme HealthKitBridge \
            -destination "platform=iOS Simulator,id=$UDID" \
            -derivedDataPath ios/build \
            -only-testing "PerformanceMonitorTests" || echo "Performance tests completed"

          xcrun simctl shutdown "$UDID" 2>/dev/null || true
          xcrun simctl delete "$UDID" 2>/dev/null || true

      - name: Upload Performance Results
        uses: actions/upload-artifact@v4
        with:
          name: performance-results
          path: ios/build/Logs/Test/*.xcresult
          retention-days: 14
