name: iOS Testing Simple

on:
  push:
    branches: [main, develop]
    paths:
      - 'ios/**'
      - '.github/workflows/ios-tests-simple.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'ios/**'

env:
  XCODE_VERSION: '16.1'

jobs:
  test:
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        test-type: ['unit', 'ui']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Cache Xcode Derived Data
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ios/build
          key: xcode-${{ runner.os }}-${{ env.XCODE_VERSION }}-simple-${{ hashFiles('ios/**/*.swift', 'ios/**/*.plist', 'ios/**/*.xcconfig') }}

      - name: Build for Testing
        run: |
          echo "Building for iOS testing with simplified destination..."
          
          # Use a simple, reliable destination
          DESTINATION="platform=iOS Simulator,name=iPhone 16 Pro"
          echo "Using destination: $DESTINATION"

          # Build for testing
          xcodebuild build-for-testing \
            -project ios/HealthKitBridge.xcodeproj \
            -scheme HealthKitBridge \
            -destination "$DESTINATION" \
            -derivedDataPath ios/build \
            -configuration Debug \
            -enableCodeCoverage YES \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ENABLE_BITCODE=NO \
            ONLY_ACTIVE_ARCH=YES

      - name: Run Tests
        run: |
          echo "Running tests with simple destination..."
          
          DESTINATION="platform=iOS Simulator,name=iPhone 16 Pro"
          echo "Using destination: $DESTINATION"

          if [ "${{ matrix.test-type }}" == "unit" ]; then
            TEST_SCHEME="HealthKitBridgeTests"
          else
            TEST_SCHEME="HealthKitBridgeUITests"
          fi

          xcodebuild test-without-building \
            -project ios/HealthKitBridge.xcodeproj \
            -scheme HealthKitBridge \
            -destination "$DESTINATION" \
            -derivedDataPath ios/build \
            -enableCodeCoverage YES \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
